### ISSUE TITLE
undefined is not an object (evaluating 'reactNative.View.propTypes.style')

### ISSUE THREAD

**Issue by IndustryNicheApps** [rimiti/react-native-pickerise#1]
I am using expo v23 and i am getting this error (red screen) when running the app through the expo client not in development mode. 

undefined is not an object (evaluating 'reactNative.View.propTypes.style')

<img width="375" alt="screen" src="https://user-images.githubusercontent.com/34637081/34439947-b70bfeb6-ec7f-11e7-821e-212a13d5021a.png">

**Comment by IndustryNicheApps** [comment]
I was able to fix it locally by replacing the View.propTypes with ViewPropTypes imported from react-native

**Comment by rimiti** [comment]
Hello,

Thank you for your issue.
I think, this case is caused because react-native has not been set as a peer dependency.

What's your RN version ?

I'll try to fixe it today.
I keep in touch you.

**Comment by rimiti** [comment]
Hello @IndustryNicheApps, 

It has been fixed:  https://github.com/rimiti/react-native-pickerise/commit/34b932063eebb977a567f5364f6da260a328840e

Have a nice day,
Dimitri

**Comment by yusney** [comment]
I have this same problem how can I solve it please

**Comment by rimiti** [comment]
@yusney: are you using the last version ?

**Comment by yusney** [comment]
Thanks it was a problem with the version

**Comment by rimiti** [comment]
Happy to know it!
